### ISSUE TITLE
Run test after train

### ISSUE THREAD

**Issue by rezashami** [rhaksar/ddrl-firefighting#1]
Hi,
In this line I get an error. If I run train section, and close the program and run test section in other program environment, I get an error that says "self.num_train_episodes" not defined. Please fix this issue.
Thanks

https://github.com/rhaksar/ddrl-firefighting/blob/01df1d953ae7b7cd35a7fc855fd67a65499b1967/madqn.py#L193

**Comment by rhaksar** [comment]
Hi, I'm having trouble reproducing your exact issue. I am able to run the following code using a network written to file:
```
load_filename =   # network filename as string
test_method = 'network'
algorithm = MADQN(mode='test', filename=load_filename)
results = algorithm.test(num_episodes=1, method=test_method)
```

I did find an error in loading a network from file to continue training, which I fixed on the branch `load_checkpoint_fix`. Let me know if this branch fixes your issue or not.
